# -*- coding: utf-8 -*-
"""Fin_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ai8l7oFwXfONYSeCvb4VI9GfltZyK50E

# **TA-Lib prepare for working with Colab area**
"""

# download TA-Lib 
!wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz

!ls

!tar xvzf ta-lib-0.4.0-src.tar.gz

!ls

import os

os.chdir('ta-lib') # Can't use !cd in co-lab

!./configure --prefix=/usr

!make

!make install

os.chdir('../')

!ls

!pip install TA-Lib

"""# **Start working with TA-Lib**"""

import talib
import numpy as np
import pandas as pd

pip install mpl_finance

pip install yfinance

pip install plotly

import yfinance as yf
df = yf.download("INTC", start="2020-01-01", end="2020-07-01")
df.reset_index(drop=False, inplace=True)

dates = df[df.columns[0]]

Open = df['Open'].values
High = df['High'].values
Low = df['Low'].values
Close = df['Close'].values
result = talib.CDLHAMMER(Open,High,Low,Close)
#result = talib.CDLHARAMICROSS(Open,High,Low,Close)
#result = talib.CDLCONCEALBABYSWALL(Open,High,Low,Close)

result

print("We are doing data analysis for Hummer Candlestick")
days = np.where(result != 0)[0]
for i in days :
  if result[i] == 100:
    print("The date",dates[i],"is Bullish")
  if result[i] == -100:
    print("The date",dates[i],"is Bearish")

# You can check the dates where the specific Candlestick happened
import plotly.graph_objects as go
import pandas as pd
from datetime import datetime
fig = go.Figure(data=[go.Candlestick(x=df['Date'],
                open=df['Open'],
                high=df['High'],
                low=df['Low'],
                close=df['Close'])])
fig.show()

"""## **All Candlestick Models**"""

#CDL2CROWS            Two Crows
#CDL3BLACKCROWS       Three Black Crows
#CDL3INSIDE           Three Inside Up/Down
#CDL3LINESTRIKE       Three-Line Strike
#CDL3OUTSIDE          Three Outside Up/Down
#CDL3STARSINSOUTH     Three Stars In The South
#CDL3WHITESOLDIERS    Three Advancing White Soldiers
#CDLABANDONEDBABY     Abandoned Baby
#CDLADVANCEBLOCK      Advance Block
#CDLBELTHOLD          Belt-hold
#CDLBREAKAWAY         Breakaway
#CDLCLOSINGMARUBOZU   Closing Marubozu
#CDLCONCEALBABYSWALL  Concealing Baby Swallow
#CDLCOUNTERATTACK     Counterattack
#CDLDARKCLOUDCOVER    Dark Cloud Cover
#CDLDOJI              Doji
#CDLDOJISTAR          Doji Star
#CDLDRAGONFLYDOJI     Dragonfly Doji
#CDLENGULFING         Engulfing Pattern
#CDLEVENINGDOJISTAR   Evening Doji Star
#CDLEVENINGSTAR       Evening Star
#CDLGAPSIDESIDEWHITE  Up/Down-gap side-by-side white lines
#CDLGRAVESTONEDOJI    Gravestone Doji
#CDLHAMMER            Hammer
#CDLHANGINGMAN        Hanging Man
#CDLHARAMI            Harami Pattern
#CDLHARAMICROSS       Harami Cross Pattern *******
#CDLHIGHWAVE          High-Wave Candle
#CDLHIKKAKE           Hikkake Pattern
#CDLHIKKAKEMOD        Modified Hikkake Pattern
#CDLHOMINGPIGEON      Homing Pigeon
#CDLIDENTICAL3CROWS   Identical Three Crows
#CDLINNECK            In-Neck Pattern
#CDLINVERTEDHAMMER    Inverted Hammer
#CDLKICKING           Kicking
#CDLKICKINGBYLENGTH   Kicking - bull/bear determined by the longer marubozu
#CDLLADDERBOTTOM      Ladder Bottom
#CDLLONGLEGGEDDOJI    Long Legged Doji
#CDLLONGLINE          Long Line Candle
#CDLMARUBOZU          Marubozu
#CDLMATCHINGLOW       Matching Low
#CDLMATHOLD           Mat Hold
#CDLMORNINGDOJISTAR   Morning Doji Star *****
#CDLMORNINGSTAR       Morning Star
#CDLONNECK            On-Neck Pattern
#CDLPIERCING          Piercing Pattern ******
#CDLRICKSHAWMAN       Rickshaw Man
#CDLRISEFALL3METHODS  Rising/Falling Three Methods
#CDLSEPARATINGLINES   Separating Lines
#CDLSHOOTINGSTAR      Shooting Star
#CDLSHORTLINE         Short Line Candle
#CDLSPINNINGTOP       Spinning Top
#CDLSTALLEDPATTERN    Stalled Pattern
#CDLSTICKSANDWICH     Stick Sandwich
#CDLTAKURI            Takuri (Dragonfly Doji with very long lower shadow)
#CDLTASUKIGAP         Tasuki Gap
#CDLTHRUSTING         Thrusting Pattern
#CDLTRISTAR           Tristar Pattern
#CDLUNIQUE3RIVER      Unique 3 River
#CDLUPSIDEGAP2CROWS   Upside Gap Two Crows
#CDLXSIDEGAP3METHODS  Upside/Downside Gap Three Methods